### ISSUE TITLE
404 error for listing products.

### ISSUE THREAD

**Issue by c7ming** [WalkingPizza/strapi-plugin-shopify-fields#1]
Hi.
Firstly, I'd like to express my gratitude for developing such an awesome product.

I've attempted to incorporate it into my project. However, I'm experiencing a '404 response error' with the Shopify-node-api. After examining the source code, I found that my configuration was setted successfully. Here's the URL generated by the package:

`{
  pathname: "/admin/api/2022-06/products.json",
  hostname: "**.myshopify.com",
  protocol: "https:",
  search: "?limit=12&fields=image%2Ctitle%2Cid",
}`

Could you help me a bit?

And here is the plugin setting
`
export default ({ env }) => ({
    'shopify-fields': {
        enabled: true,
        config: {
        apiVersion: '2022-06', // Or one of Shopify's supported API versions
        accessToken: env('SHOPIFY_ACCESS_TOKEN', ''), // The environment variable containing your private app's access token
        shopName: env('SHOP_NAME', ''), // The environment variable containing your myshopify.com domain
        },
    },
});
`

**Comment by WalkingPizza** [comment]
Hey @c7ming, thanks for opening this issue!

Could you please edit it by including some more information about the problem you are currently facing and your current setup?

A few screenshots would be greatly appreciated too.

**Comment by c7ming** [comment]
Sorry, the comment was updated.

**Comment by WalkingPizza** [comment]
You are using an unsupported value for `apiVersion`.
[Here](https://shopify.dev/api/usage/versioning)'s a list of supported options.

**Comment by c7ming** [comment]
Ah...... Thanks!!!
